name: nlmod

on:
  # Trigger the workflow on push or pull request on main,
  # and only on pull-requests on dev branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics

      - name: Download executables needed for tests
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Needed for downloading executables
          NLMOD_SUPPRESS_EXE_VERION_CHECK: "True"
        shell: bash -l {0}
        run: |
          python -c "import nlmod; nlmod.util.download_mfbinaries()"

      - name: Run tests only
        env:
            NHI_GWO_USERNAME: ${{ secrets.NHI_GWO_USERNAME}}
            NHI_GWO_PASSWORD: ${{ secrets.NHI_GWO_PASSWORD}}
            GITHUB_TOKEN: ${{ github.token }}  # Needed for downloading executables
            NLMOD_SUPPRESS_EXE_VERION_CHECK: "True"
        run: |
          py.test ./tests -m "not notebooks"

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
